-- MySQL Script generated by MySQL Workbench
-- Mon Apr  1 13:27:30 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chefVirtual
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chefVirtual
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chefVirtual` DEFAULT CHARACTER SET utf8 ;
USE `chefVirtual` ;

-- -----------------------------------------------------
-- Table `chefVirtual`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chefVirtual`.`usuario` (
  `uuid` CHAR(36) NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `fotoUsuariocol` VARCHAR(50) NULL,
  `tipoUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`uuid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chefVirtual`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chefVirtual`.`categoria` (
  `uuid` CHAR(36) NOT NULL,
  `nomeCategoria` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`uuid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chefVirtual`.`prato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chefVirtual`.`prato` (
  `uuid` CHAR(36) NOT NULL,
  `nome` VARCHAR(120) NOT NULL,
  `descricao` VARCHAR(150) NOT NULL,
  `custo` FLOAT NOT NULL,
  `tempoPreparo` VARCHAR(45) NOT NULL,
  `observacoes` VARCHAR(150) NULL,
  `foto` VARCHAR(50) NULL,
  `categoria_uuid` CHAR(36) NOT NULL,
  `usuario_uuid` CHAR(36) NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `fk_prato_usuario1_idx` (`usuario_uuid` ASC) ,
  INDEX `fk_prato_categoria1_idx` (`categoria_uuid` ASC) ,
  CONSTRAINT `fk_prato_usuario1`
    FOREIGN KEY (`usuario_uuid`)
    REFERENCES `chefVirtual`.`usuario` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prato_categoria1`
    FOREIGN KEY (`categoria_uuid`)
    REFERENCES `chefVirtual`.`categoria` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chefVirtual`.`materiais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chefVirtual`.`materiais` (
  `uuid` CHAR(36) NOT NULL,
  `nomeMaterial` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`uuid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chefVirtual`.`favoritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chefVirtual`.`favoritos` (
  `uuid` CHAR(36) NOT NULL,
  `usuario_uuid` CHAR(36) NOT NULL,
  `prato_uuid` CHAR(36) NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `fk_favoritos_usuario1_idx` (`usuario_uuid` ASC) ,
  INDEX `fk_favoritos_prato1_idx` (`prato_uuid` ASC) ,
  CONSTRAINT `fk_favoritos_usuario1`
    FOREIGN KEY (`usuario_uuid`)
    REFERENCES `chefVirtual`.`usuario` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favoritos_prato1`
    FOREIGN KEY (`prato_uuid`)
    REFERENCES `chefVirtual`.`prato` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chefVirtual`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chefVirtual`.`avaliacao` (
  `uuid` CHAR(36) NOT NULL,
  `avaliacaoDoPrato` VARCHAR(200) NOT NULL,
  `data` DATE NOT NULL,
  `usuario_uuid` CHAR(36) NOT NULL,
  `prato_uuid` CHAR(36) NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `fk_avaliacao_usuario1_idx` (`usuario_uuid` ASC) ,
  INDEX `fk_avaliacao_prato1_idx` (`prato_uuid` ASC) ,
  CONSTRAINT `fk_avaliacao_usuario1`
    FOREIGN KEY (`usuario_uuid`)
    REFERENCES `chefVirtual`.`usuario` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_prato1`
    FOREIGN KEY (`prato_uuid`)
    REFERENCES `chefVirtual`.`prato` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chefVirtual`.`indredientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chefVirtual`.`indredientes` (
  `uuid` CHAR(36) NOT NULL,
  `NomeIndrediente` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`uuid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chefVirtual`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chefVirtual`.`log` (
  `uuid` CHAR(36) NOT NULL,
  `data` DATETIME NOT NULL,
  `prato_uuid` CHAR(36) NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `fk_log_prato1_idx` (`prato_uuid` ASC) ,
  CONSTRAINT `fk_log_prato1`
    FOREIGN KEY (`prato_uuid`)
    REFERENCES `chefVirtual`.`prato` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chefVirtual`.`materiais_has_prato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chefVirtual`.`materiais_has_prato` (
  `materiais_uuid` CHAR(36) NOT NULL,
  `prato_uuid` CHAR(36) NOT NULL,
  PRIMARY KEY (`materiais_uuid`, `prato_uuid`),
  INDEX `fk_materiais_has_prato_prato1_idx` (`prato_uuid` ASC) ,
  INDEX `fk_materiais_has_prato_materiais1_idx` (`materiais_uuid` ASC) ,
  CONSTRAINT `fk_materiais_has_prato_materiais1`
    FOREIGN KEY (`materiais_uuid`)
    REFERENCES `chefVirtual`.`materiais` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materiais_has_prato_prato1`
    FOREIGN KEY (`prato_uuid`)
    REFERENCES `chefVirtual`.`prato` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chefVirtual`.`prato_has_indredientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chefVirtual`.`prato_has_indredientes` (
  `prato_uuid` CHAR(36) NOT NULL,
  `indredientes_uuid` CHAR(36) NOT NULL,
  `quantidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`prato_uuid`, `indredientes_uuid`),
  INDEX `fk_prato_has_indredientes_indredientes1_idx` (`indredientes_uuid` ASC) ,
  INDEX `fk_prato_has_indredientes_prato1_idx` (`prato_uuid` ASC) ,
  CONSTRAINT `fk_prato_has_indredientes_prato1`
    FOREIGN KEY (`prato_uuid`)
    REFERENCES `chefVirtual`.`prato` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prato_has_indredientes_indredientes1`
    FOREIGN KEY (`indredientes_uuid`)
    REFERENCES `chefVirtual`.`indredientes` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
