-------comando para introduzir os materias-----
INSERT INTO materiais (nomeMaterial) VALUES
('Tigela'),
('Faca'),
('Colher de sopa'),
('Colher de chá'),
('Prato'),
('Panela'),
('Frigideira'),
('Assadeira'),
('Forma de bolo'),
('Espátula'),
('Concha'),
('Escumadeira'),
('Peneira'),
('Ralador'),
('Espremedor de alho'),
('Espremedor de batata'),
('Descascador de legumes'),
('Afiador de facas'),
('Amassador de carne'),
('Batedor de ovos'),
('Coador'),
('Cortador de pizza'),
('Descaroçador de azeitona'),
('Descascador de laranja'),
('Escorredor de macarrão'),
('Fouet (batedor de arame)'),
('Funil'),
('Medidor de líquidos'),
('Medidor de ingredientes secos'),
('Moedor de pimenta'),
('Passador de purê'),
('Rodo para pizza'),
('Tábua de corte'),
('Tesoura de cozinha'),
('Travessa'),
('Pincel de cozinha'),
('Luvas térmicas'),
('Termômetro culinário'),
('Papel alumínio'),
('Papel manteiga'),
('Papel filme (plástico filme)'),
('Palitos de dente'),
('Rolo de massa'),
('Espátula de silicone'),
('Ralador de queijo'),
('Forma de muffin'),
('Forma de pizza'),
('Cortador de biscoitos'),
('Saco de confeitar'),
('Tapete de silicone para assar'),
('Colher de sorvete'),
('Pá de pizza'),
('Forma de cupcake'),
('Pinça de cozinha'),
('Escova de limpeza de vegetais'),
('Abridor de latas'),
('Descascador de maçã'),
('Cortador de massa'),
('Prensa de alho'),
('Saco para congelamento'),
('Moedor de alho'),
('Espremedor de limão'),
('Dosador de massa para biscoitos'),
('Raspador de bancada'),
('Prato de servir'),
('Balança de cozinha'),
('Peneira fina'),
('Pá de confeiteiro'),
('Forma de torta'),
('Molde de silicone para chocolate'),
('Copo medidor ajustável'),
('Colher medidora ajustável'),
('Peneira de farinha'),
('Pá de massa'),
('Forma de pão'),
('Batedor de mão'),
('Abridor de garrafas'),
('Rolha de silicone'),
('Descascador de camarão'),
('Batedor de arame'),
('Pinça de gelo'),
('Moedor de especiarias'),
('Acessórios para sushi'),
('Açucareiro'),
('Coador de chá'),
('Espremedor de limão'),
('Descaroçador de cerejas'),
('Descaroçador de azeitonas'),
('Descaroçador de pêssegos'),
('Descascador de abacaxi'),
('Escorredor de salada'),
('Faca para queijo'),
('Forma de gelo'),
('Forma de silicone'),
('Forma para ovo poché'),
('Manteigueira'),
('Pilão'),
('Porta-guardanapos'),
('Quebra-nozes'),
('Régua de medição'),
('Sacola de compras reutilizável'),
('Sifão de chantilly'),
('Torrador de pimentão'),
('Triturador de alho'),
('Cobridor de alimento'),
('Pente para decorar bolos'),
('Cortador de massa'),
('Almofariz'),
('Coador de leite'),
('Colher para arroz'),
('Tábua de carnes'),
('Tábua para sushi'),
('Cortador de ovo'),
('Afiador de facas'),
('Frigideira antiaderente'),
('Pote de armazenamento de alimentos'),
('Prato de servir sobremesa'),
('Aparelho para preparar massa'),
('Saca-rolhas'),
('Açucareiro com tampa'),
('Mixer de alimentos'),
('Cremeira'),
('Ralador de gengibre'),
('Raspador de limão'),
('Abridor de garrafas de vinho'),
('Jarra de medida'),
('Assadeira de vidro'),
('Luva térmica'),
('Espremedor de limão'),
('Medidor de porções'),
('Medidor de água'),
('Medidor de massa'),
('Medidor de capacidade'),
('Medidor de volume'),
('Medidor de peso'),
('Medidor de tempo'),
('Espátula de metal'),
('Conjunto de facas de cozinha'),
('Descascador de frutas'),
('Cortador de legumes em espiral'),
('Descanso de panela'),
('Escumadeira de nylon'),
('Luvas de segurança para cortar'),
('Tesoura multiuso'),
('Descaroçador de maçã'),
('Descaroçador de pêssego'),
('Descaroçador de cereja'),
('Descaroçador de ameixa'),
('Molde para hambúrguer'),
('Pincel de churrasco'),
('Rodo para pizza'),
('Pinça para grelha'),
('Faca de pão serrilhada'),
('Mandolina de cozinha'),
('Suporte para papel-toalha'),
('Garrafa de spray de azeite'),
('Espremedor de lima'),
('Raspador de peixe'),
('Amassador de batata'),
('Aerador de vinho'),
('Coador de gotejamento de café'),
('Bandeja de gelo flexível'),
('Espiralizador de vegetais'),
('Moedor de queijo'),
('Medidor de temperatura do forno'),
('Faca de descascar'),
('Conjunto de colheres medidoras'),
('Conjunto de copos medidores'),
('Jarra medidora'),
('Balança de cozinha digital'),
('Batedor de claras em neve'),
('Forma para sushi'),
('Molde de ovo poché'),
('Descanso de colher'),
('Coador de iogurte'),
('Forma de muffin de silicone'),
('Espátula de silicone para panela'),
('Coador de macarrão'),
('Arame para assar');



